server:
  port: 8081
spring:
  application:
    name: content-service
  datasource:
    # FIX: Point to localhost and use port 3309!
    url: jdbc:mysql://localhost:3309/content_db
    username: root
    password: nikhil
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true