spring:
  application:
    name: user_service
  datasource:
    url: jdbc:mysql://mysql-user:3306/user_db
    username: root
    password: nikhil
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
